// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDism6zJ5VH09YW1oIMqJAFZKN-GoySEY',
    appId: '1:844966549700:web:ae66c0302afe8d249e9191',
    messagingSenderId: '844966549700',
    projectId: 'footballmanager-bce7e',
    authDomain: 'footballmanager-bce7e.firebaseapp.com',
    storageBucket: 'footballmanager-bce7e.firebasestorage.app',
    databaseURL: 'https://footballmanager-bce7e-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDism6zJ5VH09YW1oIMqJAFZKN-GoySEY',
    appId: '1:844966549700:android:ae66c0302afe8d249e9191',
    messagingSenderId: '844966549700',
    projectId: 'footballmanager-bce7e',
    storageBucket: 'footballmanager-bce7e.firebasestorage.app',
    databaseURL: 'https://footballmanager-bce7e-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDism6zJ5VH09YW1oIMqJAFZKN-GoySEY',
    appId: '1:844966549700:ios:ae66c0302afe8d249e9191',
    messagingSenderId: '844966549700',
    projectId: 'footballmanager-bce7e',
    storageBucket: 'footballmanager-bce7e.firebasestorage.app',
    databaseURL: 'https://footballmanager-bce7e-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.phoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDism6zJ5VH09YW1oIMqJAFZKN-GoySEY',
    appId: '1:844966549700:ios:ae66c0302afe8d249e9191',
    messagingSenderId: '844966549700',
    projectId: 'footballmanager-bce7e',
    storageBucket: 'footballmanager-bce7e.firebasestorage.app',
    databaseURL: 'https://footballmanager-bce7e-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.phoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDism6zJ5VH09YW1oIMqJAFZKN-GoySEY',
    appId: '1:844966549700:web:ae66c0302afe8d249e9191', // Windows uses same format as web often, or just requires any valid ID
    messagingSenderId: '844966549700',
    projectId: 'footballmanager-bce7e',
    authDomain: 'footballmanager-bce7e.firebaseapp.com',
    storageBucket: 'footballmanager-bce7e.firebasestorage.app',
    databaseURL: 'https://footballmanager-bce7e-default-rtdb.firebaseio.com',
  );
}
